name: json_inspector
description: "An interactive Flutter JSON viewer with expand/collapse, value selection, and copy-to-clipboard features. Ideal for debugging, inspecting, and visualizing JSON data."
version: 2.0.0
homepage: "https://github.com/Neelansh-ns/json_inspector"
repository: "https://github.com/Neelansh-ns/json_inspector"
topics:
  - json
  - debug
  - inspector
screenshots:
  - description: "JSON Inspector"
    path: screenshots/json_inspector.png

environment:
  sdk: '>=3.5.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^5.0.0
  flutter_lints: ^5.0.0


  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
